<a href="https://colab.research.google.com/github/RocioLiu/AI-for-Trading/blob/main/Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving data.csv to data.csv


In [5]:
import numpy as np
import pandas as pd
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

In [9]:
data = pd.read_csv('data.csv', header=None)
data.head()

0         1  2
0  0.78051 -0.063669  1
1  0.28774  0.291390  1
2  0.40714  0.178780  1
3  0.29230  0.421700  1
4  0.50922  0.352560  1

In [12]:
X = np.array(data.iloc[:, :2])
print(X[:5])

[[ 0.78051  -0.063669]
 [ 0.28774   0.29139 ]
 [ 0.40714   0.17878 ]
 [ 0.2923    0.4217  ]
 [ 0.50922   0.35256 ]]


In [16]:
y = np.array(data.iloc[:, 2])
print(y[:5])

[1 1 1 1 1]


In [17]:
def stepFunction(t):
    if t >= 0:
        return 1
    return 0

In [18]:
def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

In [19]:
# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    # Fill in code
    
    for i in range(len(X)):
        y_hat = prediction(X[i], W, b)
        if (y_hat - y[i]) == 0:
            continue
        elif (y_hat - y[i]) > 0:
            W[0] = W[0] - learn_rate * X[i][0]
            W[1] = W[1] - learn_rate * X[i][1]
            b = b - learn_rate
        else:
            W[0] = W[0] + learn_rate * X[i][0]
            W[1] = W[1] + learn_rate * X[i][1]
            b = b + learn_rate
    return W, b

In [20]:
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

In [32]:
boundary_lines = trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25)
boundary_lines[:5]

[(array([1.10978832]), array([4.46888546])),
 (array([0.03241705]), array([1.42964659])),
 (array([-0.22131743]), array([0.73284983])),
 (array([-0.24498341]), array([0.6751207])),
 (array([-0.26118871]), array([0.64953538]))]

![perceptron](https://raw.githubusercontent.com/RocioLiu/AI-for-Trading/main/2.%20AI%20Algorithms%20in%20Trading/L8_Intro-to-Neural-Networks/perceptron.jpg)